name = "ProgressTables"
uuid = "e0b4b9f6-8cc7-451e-9c86-94c5316e9f73"
authors = ["raphasampaio"]
version = "0.2.0"

[deps]
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[compat]
Aqua = "0.7, 0.8"
Printf = "1.9 - 1.12"
Test = "1.9 - 1.12"
julia = "1.9"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Test"]
